
apiVersion: v1
kind: ConfigMap
metadata:
  name: hive-config
data:
  NODE_ENV: production
  REDIS_HOST: redis
  POSTGRES_HOST: postgres
  CLICKHOUSE_HOST: clickhouse
  KAFKA_BROKER: kafka:9092
  MINIO_ENDPOINT: http://minio:9000
