
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: ghcr.io/kamilkisiela/graphql-hive:latest
          command: ["pnpm", "start:kafka"]
          ports:
            - containerPort: 4000
