
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: ghcr.io/kamilkisiela/graphql-hive:latest
          command: ["pnpm", "start:minio"]
          ports:
            - containerPort: 4000
