
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hive-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/hive"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hive-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
