
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse
  labels:
    app: clickhouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
        - name: clickhouse
          image: ghcr.io/kamilkisiela/graphql-hive:latest
          command: ["pnpm", "start:clickhouse"]
          ports:
            - containerPort: 4000
